d = dict(a=1, b=2)
print(len(d), d.get("a"), d.get("z"), d.get("z", 7))
d.update([("a", 4)], c=3)
print(d["a"], d["b"], d["c"])
print(d.setdefault("x", 9), d.setdefault("x", 8))
print(d.pop("a"), d.pop("missing", "fallback"))
c = d.copy()
d.clear()
print(len(d), len(c), c["x"])
f = dict.fromkeys("aba", [])
f["a"].append(5)
print(len(f), len(f["b"]))
