print(min('bca'), max('bca'), min((3, 1, 2)), max((3, 1, 2)))
print(min([(2,), (1, 3), (1, 2)]), max([(1,), (1, 0)]))
print(sorted([(2, 'b'), (1, 'z'), (1, 'a')]))
print(sorted([2.5, 1, -1.5, 2]), sorted('cba'))
print(list(reversed((1, 2, 3))), tuple(reversed('abc')))
print(list('ab'), tuple('ab'), list(()), tuple([]))
print([1, 2] < [1, 3], [1] <= [1], [1, 0] > [1], [1] >= [1])
print((1, 2) < (1, 3), (1,) <= (1,), (1, 0) > (1,), (1,) >= (1,))
print('abc' < 'abd', 'abc' <= 'abc', 'abcd' > 'abc', 'abc' >= 'abc')
