# Ported from examples/lumen/string_library_demo.lm by scripts/port_examples.py; edit the Lumen original, not this file.
puts("=== String Library Examples ===")
puts("")
text = "Hello World"
print("Original: ")
puts(text)
print("substring(text, 0, 5): ")
puts(substring(text, 0, 5))
print("substring(text, 6, 11): ")
puts(substring(text, 6, 11))
puts("")
print("substring_end(text, 6): ")
puts(substring_end(text, 6))
puts("")
print("substring_start(text, 5): ")
puts(substring_start(text, 5))
puts("")
print("starts_with('Hello World', 'Hello'): ")
puts(starts_with(text, "Hello"))
print("starts_with('Hello World', 'World'): ")
puts(starts_with(text, "World"))
puts("")
print("ends_with('Hello World', 'World'): ")
puts(ends_with(text, "World"))
print("ends_with('Hello World', 'Hello'): ")
puts(ends_with(text, "Hello"))
puts("")
print("repeat_string('Ha', 5): ")
puts(repeat_string("Ha", 5))
print("repeat_string('-=', 10): ")
puts(repeat_string("-=", 10))
puts("")
fruits = ["apple", "banana", "cherry"]
print("join_strings(['apple', 'banana', 'cherry'], ', '): ")
puts(join_strings(fruits, ", "))
print("join_strings(['apple', 'banana', 'cherry'], ' | '): ")
puts(join_strings(fruits, " | "))
puts("")
sentence = "The quick brown fox jumps over the lazy dog"
print("index_of('The quick brown fox...', 'fox'): ")
puts(index_of(sentence, "fox"))
print("index_of('The quick brown fox...', 'cat'): ")
puts(index_of(sentence, "cat"))
puts("")
print("has_substring('The quick brown fox...', 'quick'): ")
puts(has_substring(sentence, "quick"))
print("has_substring('The quick brown fox...', 'slow'): ")
puts(has_substring(sentence, "slow"))
puts("")
puts("=== Practical Example ===")
name = "Lumen"
version = "1.0"
description = "A minimal language"
separator = repeat_string("-", 40)
puts(separator)
info = "Project: " + name
puts(info)
info2 = "Version: " + version
puts(info2)
info3 = "Description: " + description
puts(info3)
puts(separator)
