// Ported from examples/lumen/string_library_demo.lm by scripts/port_examples.py; edit the Lumen original, not this file.
console.log("=== String Library Examples ===");
console.log("");
const text = "Hello World";
process.stdout.write("Original: ");
console.log(text);
process.stdout.write("substring(text, 0, 5): ");
console.log(substring(text, 0, 5));
process.stdout.write("substring(text, 6, 11): ");
console.log(substring(text, 6, 11));
console.log("");
process.stdout.write("substring_end(text, 6): ");
console.log(substring_end(text, 6));
console.log("");
process.stdout.write("substring_start(text, 5): ");
console.log(substring_start(text, 5));
console.log("");
process.stdout.write("starts_with('Hello World', 'Hello'): ");
console.log(starts_with(text, "Hello"));
process.stdout.write("starts_with('Hello World', 'World'): ");
console.log(starts_with(text, "World"));
console.log("");
process.stdout.write("ends_with('Hello World', 'World'): ");
console.log(ends_with(text, "World"));
process.stdout.write("ends_with('Hello World', 'Hello'): ");
console.log(ends_with(text, "Hello"));
console.log("");
process.stdout.write("repeat_string('Ha', 5): ");
console.log(repeat_string("Ha", 5));
process.stdout.write("repeat_string('-=', 10): ");
console.log(repeat_string("-=", 10));
console.log("");
const fruits = ["apple", "banana", "cherry"];
process.stdout.write("join_strings(['apple', 'banana', 'cherry'], ', '): ");
console.log(join_strings(fruits, ", "));
process.stdout.write("join_strings(['apple', 'banana', 'cherry'], ' | '): ");
console.log(join_strings(fruits, " | "));
console.log("");
const sentence = "The quick brown fox jumps over the lazy dog";
process.stdout.write("index_of('The quick brown fox...', 'fox'): ");
console.log(index_of(sentence, "fox"));
process.stdout.write("index_of('The quick brown fox...', 'cat'): ");
console.log(index_of(sentence, "cat"));
console.log("");
process.stdout.write("has_substring('The quick brown fox...', 'quick'): ");
console.log(has_substring(sentence, "quick"));
process.stdout.write("has_substring('The quick brown fox...', 'slow'): ");
console.log(has_substring(sentence, "slow"));
console.log("");
console.log("=== Practical Example ===");
const name = "Lumen";
const version = "1.0";
const description = "A minimal language";
const separator = repeat_string("-", 40);
console.log(separator);
const info = "Project: " + name;
console.log(info);
const info2 = "Version: " + version;
console.log(info2);
const info3 = "Description: " + description;
console.log(info3);
console.log(separator);
