import sys
# Ported from examples/lumen/string_library_demo.lm by scripts/port_examples.py; edit the Lumen original, not this file.
print("=== String Library Examples ===")
print("")
text = "Hello World"
sys.stdout.write("Original: ")
print(text)
sys.stdout.write("substring(text, 0, 5): ")
print(substring(s= text, from_start= 0, to_end= 5))
sys.stdout.write("substring(text, 6, 11): ")
print(substring(s= text, from_start= 6, to_end= 11))
print("")
sys.stdout.write("substring_end(text, 6): ")
print(substring_end(s= text, from_here= 6))
print("")
sys.stdout.write("substring_start(text, 5): ")
print(substring_start(s= text, to_here= 5))
print("")
sys.stdout.write("starts_with('Hello World', 'Hello'): ")
print(starts_with(s= text, prefix= "Hello"))
sys.stdout.write("starts_with('Hello World', 'World'): ")
print(starts_with(s= text, prefix= "World"))
print("")
sys.stdout.write("ends_with('Hello World', 'World'): ")
print(ends_with(s= text, suffix= "World"))
sys.stdout.write("ends_with('Hello World', 'Hello'): ")
print(ends_with(s= text, suffix= "Hello"))
print("")
sys.stdout.write("repeat_string('Ha', 5): ")
print(repeat_string(s= "Ha", repetitions= 5))
sys.stdout.write("repeat_string('-=', 10): ")
print(repeat_string(s= "-=", repetitions= 10))
print("")
fruits = ["apple", "banana", "cherry"]
sys.stdout.write("join_strings(['apple', 'banana', 'cherry'], ', '): ")
print(join_strings(arr= fruits, separator= ", "))
sys.stdout.write("join_strings(['apple', 'banana', 'cherry'], ' | '): ")
print(join_strings(arr= fruits, separator= " | "))
print("")
sentence = "The quick brown fox jumps over the lazy dog"
sys.stdout.write("index_of('The quick brown fox...', 'fox'): ")
print(index_of(s= sentence, needle= "fox"))
sys.stdout.write("index_of('The quick brown fox...', 'cat'): ")
print(index_of(s= sentence, needle= "cat"))
print("")
sys.stdout.write("has_substring('The quick brown fox...', 'quick'): ")
print(has_substring(s= sentence, needle= "quick"))
sys.stdout.write("has_substring('The quick brown fox...', 'slow'): ")
print(has_substring(s= sentence, needle= "slow"))
print("")
print("=== Practical Example ===")
name = "Lumen"
version = "1.0"
description = "A minimal language"
separator = repeat_string(s= "-", repetitions= 40)
print(separator)
info = "Project: " + name
print(info)
info2 = "Version: " + version
print(info2)
info3 = "Description: " + description
print(info3)
print(separator)
