// Ported from examples/lumen/constructs/string_literals.lm by scripts/port_examples.py; edit the Lumen original, not this file.
const single1 = "hello";
const single2 = "world";
console.log(single1);
console.log(single2);
const double1 = "hello";
const double2 = "world";
console.log(double1);
console.log(double2);
console.log(single1 === double1);
console.log(single2 === double2);
const escaped_single = "can't";
console.log(escaped_single);
const literal_n = "text\\nmore";
console.log(literal_n);
const literal_t = "text\\tmore";
console.log(literal_t);
const escaped_double = "can't";
console.log(escaped_double);
const newline_test = "first\nsecond";
console.log(newline_test);
const tab_test = "col1\tcol2";
console.log(tab_test);
const escaped_quote = "He said \"hello\"";
console.log(escaped_quote);
const escaped_backslash = "path\\to\\file";
console.log(escaped_backslash);
const no_interp = "${name}";
console.log(no_interp);
const no_interp2 = "{count}";
console.log(no_interp2);
const x = "10";
const no_interp3 = "The answer is ${x}";
console.log(no_interp3);
