import sys
# Python numeric example, maintained by hand: floor division and ties to even.
sys.stdout.write("=== MINIMAL // OPERATOR VALIDATION ===\n\n")
sys.stdout.write("1. Integer // Integer (positive): 17 // 5 = ")
q = 17 // 5
print(q)
sys.stdout.write("   Identity check: 17 == 5 * 3 + (17 % 5) ? ")
identity = 5 * q + (17 % 5)
print(identity == 17)
sys.stdout.write("\n")
sys.stdout.write("2. Floor division: -17 // 5 = ")
q = -17 // 5
print(q)
sys.stdout.write("   Identity check: -17 == 5 * (-4) + (-17 % 5) ? ")
identity = 5 * q + (-17 % 5)
print(identity == -17)
sys.stdout.write("\n")
sys.stdout.write("3. 17 // -5 = ")
q = 17 // -5
print(q)
sys.stdout.write("   Identity check: 17 == -5 * (-4) + (17 % -5) ? ")
identity = -5 * q + (17 % -5)
print(identity == 17)
sys.stdout.write("\n")
sys.stdout.write("4. Float // Integer: (17/3) // 2 = ")
q = (17 / 3) // 2
print(q)
sys.stdout.write("\n")
sys.stdout.write("5. Float // Float: (20/3) // (3/2) = ")
print((20 / 3) // (3 / 2))
sys.stdout.write("\n")
sys.stdout.write("6. Float // Integer: 3.5 // 2 = ")
print(3.5 // 2)
sys.stdout.write("\n")
sys.stdout.write("7. Precedence: 20 // 3 * 2 = ")
result = 20 // 3 * 2
print(result)
sys.stdout.write("   (should be 12, not 2 or other value)\n")
sys.stdout.write("\n")
sys.stdout.write("8. Division by zero: ")
sys.stdout.write("attempting 10 // 0... ")
sys.stdout.write("(should raise error below)\n")
sys.stdout.write("If you see 'Division by zero' error next, test passed.\n")
sys.stdout.write("\n")
