import sys
# Ported from examples/lumen/constructs/ord_chr.lm by scripts/port_examples.py; edit the Lumen original, not this file.
print("=== ord() and chr() Tests ===")
print("")
sys.stdout.write("ord('A'): ")
print(ord("A"))
sys.stdout.write("ord('Z'): ")
print(ord("Z"))
sys.stdout.write("ord('a'): ")
print(ord("a"))
sys.stdout.write("ord('z'): ")
print(ord("z"))
sys.stdout.write("ord('0'): ")
print(ord("0"))
sys.stdout.write("ord('9'): ")
print(ord("9"))
print("")
sys.stdout.write("ord(' '): ")
print(ord(" "))
sys.stdout.write("ord('!'): ")
print(ord("!"))
sys.stdout.write("ord('?'): ")
print(ord("?"))
print("")
sys.stdout.write("chr(65): ")
print(chr(65))
sys.stdout.write("chr(90): ")
print(chr(90))
sys.stdout.write("chr(97): ")
print(chr(97))
sys.stdout.write("chr(122): ")
print(chr(122))
sys.stdout.write("chr(48): ")
print(chr(48))
sys.stdout.write("chr(57): ")
print(chr(57))
print("")
sys.stdout.write("chr(ord('H')): ")
print(chr(ord("H")))
sys.stdout.write("ord(chr(72)): ")
print(ord(chr(72)))
print("")
sys.stdout.write("ord('Hello'): ")
print(ord("Hello"))
print("")
result = chr(72) + chr(101) + chr(108) + chr(108) + chr(111)
sys.stdout.write("chr(72).chr(101).chr(108).chr(108).chr(111): ")
print(result)
print("")
sys.stdout.write("ord(newline): ")
print(ord("\n"))
sys.stdout.write("chr(10) [newline test]: ")
result_nl = "Line1" + chr(10) + "Line2"
print(result_nl)
print("")
print("Done!")
