# Ported from examples/lumen/constructs/ord_chr.lm by scripts/port_examples.py; edit the Lumen original, not this file.
puts("=== ord() and chr() Tests ===")
puts("")
print("ord('A'): ")
puts("A".ord)
print("ord('Z'): ")
puts("Z".ord)
print("ord('a'): ")
puts("a".ord)
print("ord('z'): ")
puts("z".ord)
print("ord('0'): ")
puts("0".ord)
print("ord('9'): ")
puts("9".ord)
puts("")
print("ord(' '): ")
puts(" ".ord)
print("ord('!'): ")
puts("!".ord)
print("ord('?'): ")
puts("?".ord)
puts("")
print("chr(65): ")
puts(65.chr)
print("chr(90): ")
puts(90.chr)
print("chr(97): ")
puts(97.chr)
print("chr(122): ")
puts(122.chr)
print("chr(48): ")
puts(48.chr)
print("chr(57): ")
puts(57.chr)
puts("")
print("chr(ord('H')): ")
puts("H".ord.chr)
print("ord(chr(72)): ")
puts(72.chr.ord)
puts("")
print("ord('Hello'): ")
puts("Hello".ord)
puts("")
result = 72.chr + 101.chr + 108.chr + 108.chr + 111.chr
print("chr(72).chr(101).chr(108).chr(108).chr(111): ")
puts(result)
puts("")
print("ord(newline): ")
puts("\n".ord)
print("chr(10) [newline test]: ")
result_nl = "Line1" + 10.chr + "Line2"
puts(result_nl)
puts("")
puts("Done!")
