print(1 in [1, 2])
print(3 not in [1, 2])
print("bc" in "abcd")
print("" in "")
print("a" in {"a": 9})
print(9 in {"a": 9})
print(2 in range(5, -1, -1))
print(True in [1])
print([1] in [[True]])
print({"a": 1, "b": 2} in [{"b": 2, "a": 1}])
