// Modules kept as source until a program asks for them.
pub static MODULES: &[(&str, &str)] = &[
    ("abc", include_str!("abc.py")),
    ("collections", include_str!("collections.py")),
    ("contextlib", include_str!("contextlib.py")),
    ("copy", include_str!("copy.py")),
    ("dataclasses", include_str!("dataclasses.py")),
    ("enum", include_str!("enum.py")),
    ("functools", include_str!("functools.py")),
    ("gc", include_str!("gc.py")),
    ("io", include_str!("io.py")),
    ("itertools", include_str!("itertools.py")),
    ("math", include_str!("math.py")),
    ("operator", include_str!("operator.py")),
    ("random", include_str!("random.py")),
    ("re", include_str!("re.py")),
    ("string", include_str!("string.py")),
    ("sys", include_str!("sys.py")),
    ("test", include_str!("test/__init__.py")),
    ("test.support", include_str!("test/support/__init__.py")),
    ("test.support.import_helper", include_str!("test/support/import_helper.py")),
    ("test.support.os_helper", include_str!("test/support/os_helper.py")),
    ("test.support.script_helper", include_str!("test/support/script_helper.py")),
    ("test.support.warnings_helper", include_str!("test/support/warnings_helper.py")),
    ("textwrap", include_str!("textwrap.py")),
    ("time", include_str!("time.py")),
    ("typing", include_str!("typing.py")),
    ("unittest", include_str!("unittest.py")),
    ("warnings", include_str!("warnings.py")),
    ("weakref", include_str!("weakref.py")),
];
