<?php
// Ported from examples/lumen/constructs/ord_chr.lm by scripts/port_examples.py; edit the Lumen original, not this file.
print("=== ord() and chr() Tests ===\n");
print("\n");
print("ord('A'): ");
print(ord("A") . "\n");
print("ord('Z'): ");
print(ord("Z") . "\n");
print("ord('a'): ");
print(ord("a") . "\n");
print("ord('z'): ");
print(ord("z") . "\n");
print("ord('0'): ");
print(ord("0") . "\n");
print("ord('9'): ");
print(ord("9") . "\n");
print("\n");
print("ord(' '): ");
print(ord(" ") . "\n");
print("ord('!'): ");
print(ord("!") . "\n");
print("ord('?'): ");
print(ord("?") . "\n");
print("\n");
print("chr(65): ");
print(chr(65) . "\n");
print("chr(90): ");
print(chr(90) . "\n");
print("chr(97): ");
print(chr(97) . "\n");
print("chr(122): ");
print(chr(122) . "\n");
print("chr(48): ");
print(chr(48) . "\n");
print("chr(57): ");
print(chr(57) . "\n");
print("\n");
print("chr(ord('H')): ");
print(chr(ord("H")) . "\n");
print("ord(chr(72)): ");
print(ord(chr(72)) . "\n");
print("\n");
print("ord('Hello'): ");
print(ord("Hello") . "\n");
print("\n");
$result = chr(72) . chr(101) . chr(108) . chr(108) . chr(111);
print("chr(72).chr(101).chr(108).chr(108).chr(111): ");
print($result . "\n");
print("\n");
print("ord(newline): ");
print(ord("\n") . "\n");
print("chr(10) [newline test]: ");
$result_nl = "Line1" . chr(10) . "Line2";
print($result_nl . "\n");
print("\n");
print("Done!\n");
