print(len(dict()))
a = dict(x=1, y=2)
print(a["x"], a["y"])
b = dict(a, x=3)
print(a["x"], b["x"])
c = dict([(1, 2), (3, 4), (1, 5)])
print(len(c), c[1], c[3])
d = dict(((i, i*i) for i in range(4)))
print(len(d), d[3])
print(dict({"x": 1}, **{"x": 9})["x"])
print(dict(["ab", "cd"])["c"])
