print(len(()))
print(len((1,)))
print((1, 2)[1])
print(len(((1, 2), (3, 4))))
print((1 + 2) * 3)
print(sum((*range(3), 3, *[4, 5])))
print(sum((1, *range(2, 4))))
print(sum([a + b for a, b in ((1, 2), (3, 4))]))
print(len({i: i*i for i in (*range(4),)}))
